/**
 * generated by Xtext 2.24.0
 */
package uk.ac.kcl.inf.mdd.cf.tankwar.tankWar.impl;

import org.eclipse.emf.ecore.EClass;

import uk.ac.kcl.inf.mdd.cf.tankwar.tankWar.DirectBehaviour;
import uk.ac.kcl.inf.mdd.cf.tankwar.tankWar.TankWarPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Direct Behaviour</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class DirectBehaviourImpl extends ValueImpl implements DirectBehaviour
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected DirectBehaviourImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return TankWarPackage.Literals.DIRECT_BEHAVIOUR;
  }

} //DirectBehaviourImpl
