/**
 * generated by Xtext 2.24.0
 */
package uk.ac.kcl.inf.mdd.cf.tankwar.tankWar.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import uk.ac.kcl.inf.mdd.cf.tankwar.tankWar.EndGameBehaviour;
import uk.ac.kcl.inf.mdd.cf.tankwar.tankWar.TankWarPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>End Game Behaviour</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link uk.ac.kcl.inf.mdd.cf.tankwar.tankWar.impl.EndGameBehaviourImpl#getWin <em>Win</em>}</li>
 *   <li>{@link uk.ac.kcl.inf.mdd.cf.tankwar.tankWar.impl.EndGameBehaviourImpl#getLost <em>Lost</em>}</li>
 * </ul>
 *
 * @generated
 */
public class EndGameBehaviourImpl extends DirectBehaviourImpl implements EndGameBehaviour
{
  /**
   * The default value of the '{@link #getWin() <em>Win</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getWin()
   * @generated
   * @ordered
   */
  protected static final String WIN_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getWin() <em>Win</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getWin()
   * @generated
   * @ordered
   */
  protected String win = WIN_EDEFAULT;

  /**
   * The default value of the '{@link #getLost() <em>Lost</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLost()
   * @generated
   * @ordered
   */
  protected static final String LOST_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getLost() <em>Lost</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLost()
   * @generated
   * @ordered
   */
  protected String lost = LOST_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected EndGameBehaviourImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return TankWarPackage.Literals.END_GAME_BEHAVIOUR;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getWin()
  {
    return win;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setWin(String newWin)
  {
    String oldWin = win;
    win = newWin;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, TankWarPackage.END_GAME_BEHAVIOUR__WIN, oldWin, win));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getLost()
  {
    return lost;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setLost(String newLost)
  {
    String oldLost = lost;
    lost = newLost;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, TankWarPackage.END_GAME_BEHAVIOUR__LOST, oldLost, lost));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case TankWarPackage.END_GAME_BEHAVIOUR__WIN:
        return getWin();
      case TankWarPackage.END_GAME_BEHAVIOUR__LOST:
        return getLost();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case TankWarPackage.END_GAME_BEHAVIOUR__WIN:
        setWin((String)newValue);
        return;
      case TankWarPackage.END_GAME_BEHAVIOUR__LOST:
        setLost((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case TankWarPackage.END_GAME_BEHAVIOUR__WIN:
        setWin(WIN_EDEFAULT);
        return;
      case TankWarPackage.END_GAME_BEHAVIOUR__LOST:
        setLost(LOST_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case TankWarPackage.END_GAME_BEHAVIOUR__WIN:
        return WIN_EDEFAULT == null ? win != null : !WIN_EDEFAULT.equals(win);
      case TankWarPackage.END_GAME_BEHAVIOUR__LOST:
        return LOST_EDEFAULT == null ? lost != null : !LOST_EDEFAULT.equals(lost);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (win: ");
    result.append(win);
    result.append(", lost: ");
    result.append(lost);
    result.append(')');
    return result.toString();
  }

} //EndGameBehaviourImpl
