/**
 * generated by Xtext 2.24.0
 */
package uk.ac.kcl.inf.mdd.cf.tankwar.tankWar.impl;

import java.util.Collection;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.util.EDataTypeEList;

import uk.ac.kcl.inf.mdd.cf.tankwar.tankWar.LocalFieldInitialisations;
import uk.ac.kcl.inf.mdd.cf.tankwar.tankWar.TankWarPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Local Field Initialisations</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link uk.ac.kcl.inf.mdd.cf.tankwar.tankWar.impl.LocalFieldInitialisationsImpl#getInitialisations <em>Initialisations</em>}</li>
 * </ul>
 *
 * @generated
 */
public class LocalFieldInitialisationsImpl extends FieldInitialisationsImpl implements LocalFieldInitialisations
{
  /**
   * The cached value of the '{@link #getInitialisations() <em>Initialisations</em>}' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getInitialisations()
   * @generated
   * @ordered
   */
  protected EList<String> initialisations;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected LocalFieldInitialisationsImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return TankWarPackage.Literals.LOCAL_FIELD_INITIALISATIONS;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<String> getInitialisations()
  {
    if (initialisations == null)
    {
      initialisations = new EDataTypeEList<String>(String.class, this, TankWarPackage.LOCAL_FIELD_INITIALISATIONS__INITIALISATIONS);
    }
    return initialisations;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case TankWarPackage.LOCAL_FIELD_INITIALISATIONS__INITIALISATIONS:
        return getInitialisations();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case TankWarPackage.LOCAL_FIELD_INITIALISATIONS__INITIALISATIONS:
        getInitialisations().clear();
        getInitialisations().addAll((Collection<? extends String>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case TankWarPackage.LOCAL_FIELD_INITIALISATIONS__INITIALISATIONS:
        getInitialisations().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case TankWarPackage.LOCAL_FIELD_INITIALISATIONS__INITIALISATIONS:
        return initialisations != null && !initialisations.isEmpty();
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (initialisations: ");
    result.append(initialisations);
    result.append(')');
    return result.toString();
  }

} //LocalFieldInitialisationsImpl
