/**
 * generated by Xtext 2.24.0
 */
package uk.ac.kcl.inf.mdd.cf.tankwar.tankWar.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import uk.ac.kcl.inf.mdd.cf.tankwar.tankWar.Expression;
import uk.ac.kcl.inf.mdd.cf.tankwar.tankWar.ScreenSpecification;
import uk.ac.kcl.inf.mdd.cf.tankwar.tankWar.TankWarPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Screen Specification</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link uk.ac.kcl.inf.mdd.cf.tankwar.tankWar.impl.ScreenSpecificationImpl#getName <em>Name</em>}</li>
 *   <li>{@link uk.ac.kcl.inf.mdd.cf.tankwar.tankWar.impl.ScreenSpecificationImpl#getScreenWidth <em>Screen Width</em>}</li>
 *   <li>{@link uk.ac.kcl.inf.mdd.cf.tankwar.tankWar.impl.ScreenSpecificationImpl#getScreenHeight <em>Screen Height</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ScreenSpecificationImpl extends MinimalEObjectImpl.Container implements ScreenSpecification
{
  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The cached value of the '{@link #getScreenWidth() <em>Screen Width</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getScreenWidth()
   * @generated
   * @ordered
   */
  protected Expression screenWidth;

  /**
   * The cached value of the '{@link #getScreenHeight() <em>Screen Height</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getScreenHeight()
   * @generated
   * @ordered
   */
  protected Expression screenHeight;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ScreenSpecificationImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return TankWarPackage.Literals.SCREEN_SPECIFICATION;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, TankWarPackage.SCREEN_SPECIFICATION__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Expression getScreenWidth()
  {
    return screenWidth;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetScreenWidth(Expression newScreenWidth, NotificationChain msgs)
  {
    Expression oldScreenWidth = screenWidth;
    screenWidth = newScreenWidth;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, TankWarPackage.SCREEN_SPECIFICATION__SCREEN_WIDTH, oldScreenWidth, newScreenWidth);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setScreenWidth(Expression newScreenWidth)
  {
    if (newScreenWidth != screenWidth)
    {
      NotificationChain msgs = null;
      if (screenWidth != null)
        msgs = ((InternalEObject)screenWidth).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - TankWarPackage.SCREEN_SPECIFICATION__SCREEN_WIDTH, null, msgs);
      if (newScreenWidth != null)
        msgs = ((InternalEObject)newScreenWidth).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - TankWarPackage.SCREEN_SPECIFICATION__SCREEN_WIDTH, null, msgs);
      msgs = basicSetScreenWidth(newScreenWidth, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, TankWarPackage.SCREEN_SPECIFICATION__SCREEN_WIDTH, newScreenWidth, newScreenWidth));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Expression getScreenHeight()
  {
    return screenHeight;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetScreenHeight(Expression newScreenHeight, NotificationChain msgs)
  {
    Expression oldScreenHeight = screenHeight;
    screenHeight = newScreenHeight;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, TankWarPackage.SCREEN_SPECIFICATION__SCREEN_HEIGHT, oldScreenHeight, newScreenHeight);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setScreenHeight(Expression newScreenHeight)
  {
    if (newScreenHeight != screenHeight)
    {
      NotificationChain msgs = null;
      if (screenHeight != null)
        msgs = ((InternalEObject)screenHeight).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - TankWarPackage.SCREEN_SPECIFICATION__SCREEN_HEIGHT, null, msgs);
      if (newScreenHeight != null)
        msgs = ((InternalEObject)newScreenHeight).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - TankWarPackage.SCREEN_SPECIFICATION__SCREEN_HEIGHT, null, msgs);
      msgs = basicSetScreenHeight(newScreenHeight, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, TankWarPackage.SCREEN_SPECIFICATION__SCREEN_HEIGHT, newScreenHeight, newScreenHeight));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case TankWarPackage.SCREEN_SPECIFICATION__SCREEN_WIDTH:
        return basicSetScreenWidth(null, msgs);
      case TankWarPackage.SCREEN_SPECIFICATION__SCREEN_HEIGHT:
        return basicSetScreenHeight(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case TankWarPackage.SCREEN_SPECIFICATION__NAME:
        return getName();
      case TankWarPackage.SCREEN_SPECIFICATION__SCREEN_WIDTH:
        return getScreenWidth();
      case TankWarPackage.SCREEN_SPECIFICATION__SCREEN_HEIGHT:
        return getScreenHeight();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case TankWarPackage.SCREEN_SPECIFICATION__NAME:
        setName((String)newValue);
        return;
      case TankWarPackage.SCREEN_SPECIFICATION__SCREEN_WIDTH:
        setScreenWidth((Expression)newValue);
        return;
      case TankWarPackage.SCREEN_SPECIFICATION__SCREEN_HEIGHT:
        setScreenHeight((Expression)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case TankWarPackage.SCREEN_SPECIFICATION__NAME:
        setName(NAME_EDEFAULT);
        return;
      case TankWarPackage.SCREEN_SPECIFICATION__SCREEN_WIDTH:
        setScreenWidth((Expression)null);
        return;
      case TankWarPackage.SCREEN_SPECIFICATION__SCREEN_HEIGHT:
        setScreenHeight((Expression)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case TankWarPackage.SCREEN_SPECIFICATION__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case TankWarPackage.SCREEN_SPECIFICATION__SCREEN_WIDTH:
        return screenWidth != null;
      case TankWarPackage.SCREEN_SPECIFICATION__SCREEN_HEIGHT:
        return screenHeight != null;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (name: ");
    result.append(name);
    result.append(')');
    return result.toString();
  }

} //ScreenSpecificationImpl
