/**
 * generated by Xtext 2.24.0
 */
package uk.ac.kcl.inf.mdd.cf.tankwar.tankWar.impl;

import org.eclipse.emf.ecore.EClass;

import uk.ac.kcl.inf.mdd.cf.tankwar.tankWar.SuperModeDeclaration;
import uk.ac.kcl.inf.mdd.cf.tankwar.tankWar.TankWarPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Super Mode Declaration</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class SuperModeDeclarationImpl extends OptionSpecificationImpl implements SuperModeDeclaration
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected SuperModeDeclarationImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return TankWarPackage.Literals.SUPER_MODE_DECLARATION;
  }

} //SuperModeDeclarationImpl
