/**
 * generated by Xtext 2.24.0
 */
package uk.ac.kcl.inf.mdd.cf.tankwar.tankWar.impl;

import org.eclipse.emf.ecore.EClass;

import uk.ac.kcl.inf.mdd.cf.tankwar.tankWar.TankWarPackage;
import uk.ac.kcl.inf.mdd.cf.tankwar.tankWar.WaterObstacle;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Water Obstacle</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class WaterObstacleImpl extends ObstacleMemberImpl implements WaterObstacle
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected WaterObstacleImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return TankWarPackage.Literals.WATER_OBSTACLE;
  }

} //WaterObstacleImpl
