/**
 * generated by Xtext 2.24.0
 */
package uk.ac.kcl.inf.mdd.cf.tankwar;

import uk.ac.kcl.inf.mdd.cf.tankwar.AbstractTankWarRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class TankWarRuntimeModule extends AbstractTankWarRuntimeModule {
}
