/*
 * generated by Xtext 2.24.0
 */
package uk.ac.kcl.inf.mdd.cf.tankwar.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import uk.ac.kcl.inf.mdd.cf.tankwar.ui.internal.TankwarActivator;

public class TankWarUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return TankwarActivator.getInstance().getInjector("uk.ac.kcl.inf.mdd.cf.tankwar.TankWar");
	}

}
