/**
 * generated by Xtext 2.24.0
 */
package uk.ac.kcl.inf.mdd.cf.tankwar.ide;

import uk.ac.kcl.inf.mdd.cf.tankwar.ide.AbstractTankWarIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class TankWarIdeModule extends AbstractTankWarIdeModule {
}
