/**
 * generated by Xtext 2.24.0
 */
package uk.ac.kcl.inf.mdd.cf.tankwar.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import uk.ac.kcl.inf.mdd.cf.tankwar.TankWarRuntimeModule;
import uk.ac.kcl.inf.mdd.cf.tankwar.TankWarStandaloneSetup;
import uk.ac.kcl.inf.mdd.cf.tankwar.ide.TankWarIdeModule;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class TankWarIdeSetup extends TankWarStandaloneSetup {
  @Override
  public Injector createInjector() {
    TankWarRuntimeModule _tankWarRuntimeModule = new TankWarRuntimeModule();
    TankWarIdeModule _tankWarIdeModule = new TankWarIdeModule();
    return Guice.createInjector(Modules2.mixin(_tankWarRuntimeModule, _tankWarIdeModule));
  }
}
