/*
 * generated by Xtext 2.24.0
 */
package uk.ac.kcl.inf.mdd.cf.tankwar.ui.quickfix;


import org.eclipse.jface.text.BadLocationException;
import org.eclipse.xtext.ui.editor.model.IXtextDocument;
import org.eclipse.xtext.ui.editor.model.edit.IModification;
import org.eclipse.xtext.ui.editor.model.edit.IModificationContext;
import org.eclipse.xtext.ui.editor.quickfix.DefaultQuickfixProvider;
import org.eclipse.xtext.ui.editor.quickfix.Fix;
import org.eclipse.xtext.ui.editor.quickfix.IssueResolutionAcceptor;
import org.eclipse.xtext.validation.Issue;

import uk.ac.kcl.inf.mdd.cf.tankwar.validation.TankWarValidator;


/**
 * Custom quickfixes.
 *
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#quick-fixes
 */
public class TankWarQuickfixProvider extends DefaultQuickfixProvider {

	@Fix(TankWarValidator.INVALID_NAME)
	public void capitalizeName(final Issue issue, IssueResolutionAcceptor acceptor) {
		acceptor.accept(issue, "Capitalize name", "Capitalize the name.", "upcase.png", new IModification() {
			public void apply(IModificationContext context) throws BadLocationException {
				IXtextDocument xtextDocument = context.getXtextDocument();
				String firstLetter = xtextDocument.get(issue.getOffset(), 1);
				xtextDocument.replace(issue.getOffset(), 1, firstLetter.toUpperCase());
			}
		});
	}
	
	@Fix(TankWarValidator.INVALID_SCREEN_WIDTH)
	public void correctScreenSpecificationWidth(Issue issue, IssueResolutionAcceptor acceptor) {
		acceptor.accept(issue, "Screen initial size", "Change the screen to the initial size", "width.png", new IModification() {
			public void apply(IModificationContext context) throws BadLocationException {
				IXtextDocument xtextDocument = context.getXtextDocument();
				String widthString = xtextDocument.get(issue.getOffset(),issue.getLength());
				int width = Integer.valueOf(widthString);
				if (width<720) {
					xtextDocument.replace(issue.getOffset(), issue.getLength() , "720" );
				}else {
					xtextDocument.replace(issue.getOffset(), issue.getLength(), "1080" );
				}
			}
		});
	}
	
	@Fix(TankWarValidator.INVALID_SCREEN_HEIGHT)
	public void correctScreenSpecificationHeight(Issue issue, IssueResolutionAcceptor acceptor) {
		acceptor.accept(issue, "Screen initial size", "Change the screen to the initial size", "height.png", new IModification() {
			public void apply(IModificationContext context) throws BadLocationException {
				IXtextDocument xtextDocument = context.getXtextDocument();
				String heightString = xtextDocument.get(issue.getOffset(),issue.getLength());
				int height = Integer.valueOf(heightString);
				if (height<720) {
					xtextDocument.replace(issue.getOffset(), issue.getLength() , "720" );
				}else {
					xtextDocument.replace(issue.getOffset(), issue.getLength() , "1080" );
				}
			}
		});
	}
	
	/*
	 * @Fix(TankWarValidator.INVALID_WALL_X) public void setWallLocation(Issue
	 * issue, IssueResolutionAcceptor acceptor) { acceptor.accept(issue,
	 * "Screen initial size", "Change the screen to the initial size", "upcase.png",
	 * new IModification() { public void apply(IModificationContext context) throws
	 * BadLocationException { IXtextDocument xtextDocument =
	 * context.getXtextDocument();
	 * 
	 * xtextDocument.replace(issue.getOffset(), 1 , "720" ); } }); }
	 */
	

}
