/**
 * generated by Xtext 2.24.0
 */
package uk.ac.kcl.inf.mdd.cf.tankwar.ui.quickfix;

import org.eclipse.xtext.ui.editor.model.IXtextDocument;
import org.eclipse.xtext.ui.editor.model.edit.IModification;
import org.eclipse.xtext.ui.editor.model.edit.IModificationContext;
import org.eclipse.xtext.ui.editor.quickfix.DefaultQuickfixProvider;
import org.eclipse.xtext.ui.editor.quickfix.Fix;
import org.eclipse.xtext.ui.editor.quickfix.IssueResolutionAcceptor;
import org.eclipse.xtext.validation.Issue;
import uk.ac.kcl.inf.mdd.cf.tankwar.validation.TankWarValidator;

/**
 * Custom quickfixes.
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#quick-fixes
 */
@SuppressWarnings("all")
public class TankWarQuickfixProvider extends DefaultQuickfixProvider {
  @Fix(TankWarValidator.INVALID_NAME)
  public void capitalizeName(final Issue issue, final IssueResolutionAcceptor acceptor) {
    final IModification _function = (IModificationContext context) -> {
      IXtextDocument xtextDocument = context.getXtextDocument();
      String firstLetter = xtextDocument.get((issue.getOffset()).intValue(), 1);
      xtextDocument.replace((issue.getOffset()).intValue(), 1, firstLetter.toUpperCase());
    };
    acceptor.accept(issue, "Capitalize name", "Capitalize the name.", "upcase.png", _function);
  }
  
  @Fix(TankWarValidator.INVALID_SCREEN_WIDTH)
  public void correctScreenSpecificationWidth(final Issue issue, final IssueResolutionAcceptor acceptor) {
    final IModification _function = (IModificationContext context) -> {
      IXtextDocument xtextDocument = context.getXtextDocument();
      String widthString = xtextDocument.get((issue.getOffset()).intValue(), (issue.getLength()).intValue());
      int width = (Integer.valueOf(widthString)).intValue();
      if ((width < 720)) {
        xtextDocument.replace((issue.getOffset()).intValue(), (issue.getLength()).intValue(), "720");
      } else {
        xtextDocument.replace((issue.getOffset()).intValue(), (issue.getLength()).intValue(), "1080");
      }
    };
    acceptor.accept(issue, "Screen initial size", "Change the screen to the initial size", "width.png", _function);
  }
  
  @Fix(TankWarValidator.INVALID_SCREEN_HEIGHT)
  public void correctScreenSpecificationHeight(final Issue issue, final IssueResolutionAcceptor acceptor) {
    final IModification _function = (IModificationContext context) -> {
      IXtextDocument xtextDocument = context.getXtextDocument();
      String heightString = xtextDocument.get((issue.getOffset()).intValue(), (issue.getLength()).intValue());
      int height = (Integer.valueOf(heightString)).intValue();
      if ((height < 720)) {
        xtextDocument.replace((issue.getOffset()).intValue(), (issue.getLength()).intValue(), "720");
      } else {
        xtextDocument.replace((issue.getOffset()).intValue(), (issue.getLength()).intValue(), "1080");
      }
    };
    acceptor.accept(issue, "Screen initial size", "Change the screen to the initial size", "height.png", _function);
  }
}
