/*
 * generated by Xtext 2.24.0
 */
package uk.ac.kcl.inf.mdd.cf.tankwar.ide;


/**
 * Use this class to register ide components.
 */
public class TankWarIdeModule extends AbstractTankWarIdeModule {
}
