/**
 * generated by Xtext 2.24.0
 */
package uk.ac.kcl.inf.mdd.cf.tankwar.tankWar;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Allow Restart Menu</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see uk.ac.kcl.inf.mdd.cf.tankwar.tankWar.TankWarPackage#getAllowRestartMenu()
 * @model
 * @generated
 */
public interface AllowRestartMenu extends OptionSpecification
{
} // AllowRestartMenu
