/**
 * generated by Xtext 2.24.0
 */
package uk.ac.kcl.inf.mdd.cf.tankwar.tankWar;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Field Specification</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uk.ac.kcl.inf.mdd.cf.tankwar.tankWar.FieldSpecification#getName <em>Name</em>}</li>
 *   <li>{@link uk.ac.kcl.inf.mdd.cf.tankwar.tankWar.FieldSpecification#getEnemyCount <em>Enemy Count</em>}</li>
 * </ul>
 *
 * @see uk.ac.kcl.inf.mdd.cf.tankwar.tankWar.TankWarPackage#getFieldSpecification()
 * @model
 * @generated
 */
public interface FieldSpecification extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see uk.ac.kcl.inf.mdd.cf.tankwar.tankWar.TankWarPackage#getFieldSpecification_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link uk.ac.kcl.inf.mdd.cf.tankwar.tankWar.FieldSpecification#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Enemy Count</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Enemy Count</em>' attribute.
   * @see #setEnemyCount(int)
   * @see uk.ac.kcl.inf.mdd.cf.tankwar.tankWar.TankWarPackage#getFieldSpecification_EnemyCount()
   * @model
   * @generated
   */
  int getEnemyCount();

  /**
   * Sets the value of the '{@link uk.ac.kcl.inf.mdd.cf.tankwar.tankWar.FieldSpecification#getEnemyCount <em>Enemy Count</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Enemy Count</em>' attribute.
   * @see #getEnemyCount()
   * @generated
   */
  void setEnemyCount(int value);

} // FieldSpecification
