/**
 * generated by Xtext 2.24.0
 */
package uk.ac.kcl.inf.mdd.cf.tankwar.tankWar;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Local Field Initialisations</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uk.ac.kcl.inf.mdd.cf.tankwar.tankWar.LocalFieldInitialisations#getInitialisations <em>Initialisations</em>}</li>
 * </ul>
 *
 * @see uk.ac.kcl.inf.mdd.cf.tankwar.tankWar.TankWarPackage#getLocalFieldInitialisations()
 * @model
 * @generated
 */
public interface LocalFieldInitialisations extends FieldInitialisations
{
  /**
   * Returns the value of the '<em><b>Initialisations</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Initialisations</em>' attribute list.
   * @see uk.ac.kcl.inf.mdd.cf.tankwar.tankWar.TankWarPackage#getLocalFieldInitialisations_Initialisations()
   * @model unique="false"
   * @generated
   */
  EList<String> getInitialisations();

} // LocalFieldInitialisations
