/**
 * generated by Xtext 2.24.0
 */
package uk.ac.kcl.inf.mdd.cf.tankwar.tankWar;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>No Op Behaviour</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see uk.ac.kcl.inf.mdd.cf.tankwar.tankWar.TankWarPackage#getNoOpBehaviour()
 * @model
 * @generated
 */
public interface NoOpBehaviour extends DirectBehaviour
{
} // NoOpBehaviour
