/**
 * generated by Xtext 2.24.0
 */
package uk.ac.kcl.inf.mdd.cf.tankwar.tankWar;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see uk.ac.kcl.inf.mdd.cf.tankwar.tankWar.TankWarPackage
 * @generated
 */
public interface TankWarFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  TankWarFactory eINSTANCE = uk.ac.kcl.inf.mdd.cf.tankwar.tankWar.impl.TankWarFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Game</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Game</em>'.
   * @generated
   */
  TankWarGame createTankWarGame();

  /**
   * Returns a new object of class '<em>Value</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Value</em>'.
   * @generated
   */
  Value createValue();

  /**
   * Returns a new object of class '<em>Direct Behaviour</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Direct Behaviour</em>'.
   * @generated
   */
  DirectBehaviour createDirectBehaviour();

  /**
   * Returns a new object of class '<em>End Game Behaviour</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>End Game Behaviour</em>'.
   * @generated
   */
  EndGameBehaviour createEndGameBehaviour();

  /**
   * Returns a new object of class '<em>String Value</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>String Value</em>'.
   * @generated
   */
  StringValue createStringValue();

  /**
   * Returns a new object of class '<em>Int Value</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Int Value</em>'.
   * @generated
   */
  IntValue createIntValue();

  /**
   * Returns a new object of class '<em>Screen Specification</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Screen Specification</em>'.
   * @generated
   */
  ScreenSpecification createScreenSpecification();

  /**
   * Returns a new object of class '<em>Obstaclepecification</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Obstaclepecification</em>'.
   * @generated
   */
  Obstaclepecification createObstaclepecification();

  /**
   * Returns a new object of class '<em>Obstacle Member</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Obstacle Member</em>'.
   * @generated
   */
  ObstacleMember createObstacleMember();

  /**
   * Returns a new object of class '<em>Water Obstacle</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Water Obstacle</em>'.
   * @generated
   */
  WaterObstacle createWaterObstacle();

  /**
   * Returns a new object of class '<em>Wall Obstacle</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Wall Obstacle</em>'.
   * @generated
   */
  WallObstacle createWallObstacle();

  /**
   * Returns a new object of class '<em>Field Specification</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Field Specification</em>'.
   * @generated
   */
  FieldSpecification createFieldSpecification();

  /**
   * Returns a new object of class '<em>Field Initialisations</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Field Initialisations</em>'.
   * @generated
   */
  FieldInitialisations createFieldInitialisations();

  /**
   * Returns a new object of class '<em>Local Field Initialisations</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Local Field Initialisations</em>'.
   * @generated
   */
  LocalFieldInitialisations createLocalFieldInitialisations();

  /**
   * Returns a new object of class '<em>Option Specification</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Option Specification</em>'.
   * @generated
   */
  OptionSpecification createOptionSpecification();

  /**
   * Returns a new object of class '<em>Super Mode Declaration</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Super Mode Declaration</em>'.
   * @generated
   */
  SuperModeDeclaration createSuperModeDeclaration();

  /**
   * Returns a new object of class '<em>Start Field Declaration</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Start Field Declaration</em>'.
   * @generated
   */
  StartFieldDeclaration createStartFieldDeclaration();

  /**
   * Returns a new object of class '<em>Allow Restart Menu</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Allow Restart Menu</em>'.
   * @generated
   */
  AllowRestartMenu createAllowRestartMenu();

  /**
   * Returns a new object of class '<em>No Op Behaviour</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>No Op Behaviour</em>'.
   * @generated
   */
  NoOpBehaviour createNoOpBehaviour();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  TankWarPackage getTankWarPackage();

} //TankWarFactory
