/**
 * generated by Xtext 2.24.0
 */
package uk.ac.kcl.inf.mdd.cf.tankwar.tankWar;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Wall Obstacle</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uk.ac.kcl.inf.mdd.cf.tankwar.tankWar.WallObstacle#getWallWidth <em>Wall Width</em>}</li>
 *   <li>{@link uk.ac.kcl.inf.mdd.cf.tankwar.tankWar.WallObstacle#getWallHeight <em>Wall Height</em>}</li>
 *   <li>{@link uk.ac.kcl.inf.mdd.cf.tankwar.tankWar.WallObstacle#getWallPosX <em>Wall Pos X</em>}</li>
 *   <li>{@link uk.ac.kcl.inf.mdd.cf.tankwar.tankWar.WallObstacle#getWallPosY <em>Wall Pos Y</em>}</li>
 * </ul>
 *
 * @see uk.ac.kcl.inf.mdd.cf.tankwar.tankWar.TankWarPackage#getWallObstacle()
 * @model
 * @generated
 */
public interface WallObstacle extends ObstacleMember
{
  /**
   * Returns the value of the '<em><b>Wall Width</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Wall Width</em>' attribute.
   * @see #setWallWidth(int)
   * @see uk.ac.kcl.inf.mdd.cf.tankwar.tankWar.TankWarPackage#getWallObstacle_WallWidth()
   * @model
   * @generated
   */
  int getWallWidth();

  /**
   * Sets the value of the '{@link uk.ac.kcl.inf.mdd.cf.tankwar.tankWar.WallObstacle#getWallWidth <em>Wall Width</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Wall Width</em>' attribute.
   * @see #getWallWidth()
   * @generated
   */
  void setWallWidth(int value);

  /**
   * Returns the value of the '<em><b>Wall Height</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Wall Height</em>' attribute.
   * @see #setWallHeight(int)
   * @see uk.ac.kcl.inf.mdd.cf.tankwar.tankWar.TankWarPackage#getWallObstacle_WallHeight()
   * @model
   * @generated
   */
  int getWallHeight();

  /**
   * Sets the value of the '{@link uk.ac.kcl.inf.mdd.cf.tankwar.tankWar.WallObstacle#getWallHeight <em>Wall Height</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Wall Height</em>' attribute.
   * @see #getWallHeight()
   * @generated
   */
  void setWallHeight(int value);

  /**
   * Returns the value of the '<em><b>Wall Pos X</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Wall Pos X</em>' attribute.
   * @see #setWallPosX(int)
   * @see uk.ac.kcl.inf.mdd.cf.tankwar.tankWar.TankWarPackage#getWallObstacle_WallPosX()
   * @model
   * @generated
   */
  int getWallPosX();

  /**
   * Sets the value of the '{@link uk.ac.kcl.inf.mdd.cf.tankwar.tankWar.WallObstacle#getWallPosX <em>Wall Pos X</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Wall Pos X</em>' attribute.
   * @see #getWallPosX()
   * @generated
   */
  void setWallPosX(int value);

  /**
   * Returns the value of the '<em><b>Wall Pos Y</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Wall Pos Y</em>' attribute.
   * @see #setWallPosY(int)
   * @see uk.ac.kcl.inf.mdd.cf.tankwar.tankWar.TankWarPackage#getWallObstacle_WallPosY()
   * @model
   * @generated
   */
  int getWallPosY();

  /**
   * Sets the value of the '{@link uk.ac.kcl.inf.mdd.cf.tankwar.tankWar.WallObstacle#getWallPosY <em>Wall Pos Y</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Wall Pos Y</em>' attribute.
   * @see #getWallPosY()
   * @generated
   */
  void setWallPosY(int value);

} // WallObstacle
