/**
 * generated by Xtext 2.24.0
 */
package uk.ac.kcl.inf.mdd.cf.tankwar.tankWar;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Water Obstacle</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see uk.ac.kcl.inf.mdd.cf.tankwar.tankWar.TankWarPackage#getWaterObstacle()
 * @model
 * @generated
 */
public interface WaterObstacle extends ObstacleMember
{
} // WaterObstacle
