/*
 * generated by Xtext 2.24.0
 */
package uk.ac.kcl.inf.mdd.cf.tankwar;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class TankWarStandaloneSetup extends TankWarStandaloneSetupGenerated {

	public static void doSetup() {
		new TankWarStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
