/*
 * generated by Xtext 2.24.0
 */
package uk.ac.kcl.inf.mdd.cf.tankwar.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import uk.ac.kcl.inf.mdd.cf.tankwar.parser.antlr.internal.InternalTankWarParser;
import uk.ac.kcl.inf.mdd.cf.tankwar.services.TankWarGrammarAccess;

public class TankWarParser extends AbstractAntlrParser {

	@Inject
	private TankWarGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalTankWarParser createParser(XtextTokenStream stream) {
		return new InternalTankWarParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "TankWarGame";
	}

	public TankWarGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(TankWarGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
