/**
 * generated by Xtext 2.24.0
 */
package uk.ac.kcl.inf.mdd.cf.tankwar.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import uk.ac.kcl.inf.mdd.cf.tankwar.ui.AbstractTankWarUiModule;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class TankWarUiModule extends AbstractTankWarUiModule {
  public TankWarUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
